### ISSUE TITLE
Return back an optional tuple

### ISSUE THREAD

**Issue by robdeans** [learn-co-curriculum/swift-dictionaryBillOrSteve-lab#2]
This is jim :)

I'm not a fan of the instruction stating that you should return back an optional tuple. Makes it confusing for the reader as to what that is.

**Comment by JimCampagno** [comment]
@projectrob21 Keep up the great work! Thanks for pointing this out. I made some changes to the instructions and the Xcode project that should make this easier for anyone coming forward.
